Feature/bug compile with without itkgpu
TheInterventionCentre/NorMIT-Plan pull request #54
Opened 2017-09-28 07:45 UTC by lcoram

Should compile if do / do not have gpu turned on in ITK

2017-10-03 11:41 UTC, RafaelPalomar requested changes
It looks good. I made a few comments (see below)

2017-10-03 11:41 UTC, RafaelPalomar commented on VesselSegmentation/Logic/CMakeLists.txt
> +  ${CMAKE_CURRENT_BINARY_DIR}/..
Could we avoid the use of relative paths?

2017-10-03 11:41 UTC, RafaelPalomar commented on VesselSegmentation/Logic/itkVesselSegmentationPreProcessingFilter.h
> +
This is C++11 which should not be used in Slicer Extensions. As an alternative just declare the variable (why public??) and initialize the value in the constructor

2017-10-03 11:41 UTC, RafaelPalomar commented on VesselSegmentation/Logic/itkVesselSegmentationPreProcessingFilter.hxx
> +        std::cout << "USING GPU: " << itkGPU << std::endl;
This line is not useful. Remove it. If you want information about GPU usage do it as a message in the CMakeLists.txt

2017-10-10 02:47 UTC, lcoram commented on VesselSegmentation/Logic/CMakeLists.txt
> +  ${CMAKE_CURRENT_BINARY_DIR}/..
Don't know why this was even there, possibly left over from some problems integrating the filter initially. It has been deleted.

2017-10-10 02:48 UTC, lcoram commented on VesselSegmentation/Logic/itkVesselSegmentationPreProcessingFilter.h
> +
Cleaned this up, I should not have left it in... as I was just printing it out as a sanity check.

2017-10-10 02:48 UTC, lcoram commented on VesselSegmentation/Logic/itkVesselSegmentationPreProcessingFilter.hxx
> +        std::cout << "USING GPU: " << itkGPU << std::endl;
Deleted

2017-10-10 02:49 UTC, lcoram commented
I have pushed another commit on this branch (think this updates the pull request?). I believe it addresses the comments you had.

2017-10-12 05:59 UTC, merged